/**
 * Playbook estático — espelho do seed da Frente A (15 objeções + sinal de compra).
 *
 * Usos:
 *   • RepositorioMemoria (dev sem banco, testes determinísticos).
 *   • Fallback de emergência: se o gateway sobe e o Postgres está fora,
 *     o L0 ainda funciona com isto até o cache do playbook carregar.
 *
 * As respostas definitivas são as do banco, editadas pelo gestor no QS.
 */
import type { ObjecaoPlaybook } from "./repositorio.js";

const o = (
  id: string,
  categoriaId: string,
  categoria: string,
  titulo: string,
  exemploLead: string,
  gatilhos: string[],
  respostaCurta: string,
  severidade: ObjecaoPlaybook["severidade"] = "media",
  momento = "qualquer",
): ObjecaoPlaybook => ({
  id,
  categoriaId,
  categoria,
  titulo,
  exemploLead,
  variacoes: [],
  gatilhos,
  resposta: respostaCurta,
  respostaCurta,
  severidade,
  momento,
});

export const SEED_OBJECOES: ObjecaoPlaybook[] = [
  o("00000000-0000-4000-8000-000000000001", "preco", "Preço / Investimento",
    "Achei caro / valor acima do esperado",
    "Nossa, achei bem salgado. Esperava algo mais em conta.",
    ["achei caro", "tá caro", "muito caro", "salgado", "muito dinheiro", "acima do que eu esperava", "fora do orçamento", "tá pesado", "caro demais", "acima do orçamento"],
    "Caro comparado com o que? Vamos abrir o que compõe cada linha do pacote.", "alta", "proposta"),
  o("00000000-0000-4000-8000-000000000002", "preco", "Preço / Investimento",
    "Encontrei mais barato em site de reserva",
    "Eu vi no site de reservas bem mais barato que isso aí.",
    ["mais barato", "achei em outro site", "vi na internet", "booking", "decolar", "site de viagem", "site do hotel", "direto no hotel", "mais em conta"],
    "Me manda o print. Vou igualar o escopo linha por linha antes de comparar número.", "alta", "proposta"),
  o("00000000-0000-4000-8000-000000000003", "preco", "Preço / Investimento",
    "Não tenho esse valor disponível agora",
    "Nesse momento eu não tenho esse dinheiro em caixa.",
    ["não tenho o valor", "sem dinheiro agora", "apertado", "não cabe no orçamento", "não cabe no bolso"],
    "Me diz a parcela que cabe. Eu monto o desenho partindo dela, com prazo e data.", "alta", "fechamento"),
  o("00000000-0000-4000-8000-000000000004", "preco", "Preço / Investimento",
    "Vou montar por conta própria e sai mais barato",
    "Eu mesmo monto tudo, só pesquisar. Sai bem mais em conta.",
    ["eu mesmo monto", "por conta própria", "só pesquisar", "faço sozinho", "não preciso de agência"],
    "Você consegue montar. Me manda seu roteiro que eu aponto os três riscos que vejo nele.", "media", "diagnostico"),
  o("00000000-0000-4000-8000-000000000005", "timing", "Timing / Adiamento",
    "Vou decidir mais perto da data",
    "Deixa eu pensar, quando chegar mais perto eu te falo.",
    ["vou pensar", "mais perto", "depois eu vejo", "me dá um tempo", "ainda tá longe", "sem pressa", "preciso pensar", "pensar melhor", "depois eu te retorno", "te dou um retorno", "ver com calma"],
    "Pensa sim. Mas deixa eu travar a condição de hoje com sinal reembolsável.", "alta", "fechamento"),
  o("00000000-0000-4000-8000-000000000006", "timing", "Timing / Adiamento",
    "Esse ano está corrido, fica para o ano que vem",
    "Esse ano tá impossível. Ano que vem eu te procuro.",
    ["ano que vem", "próximo ano", "esse ano não dá", "tá corrido", "mais pra frente", "agora não"],
    "Decidir agora para viajar lá na frente é o melhor dos dois mundos: tarifa de abertura e mais parcelas.", "media", "diagnostico"),
  o("00000000-0000-4000-8000-000000000007", "timing", "Timing / Adiamento",
    "Preciso confirmar as férias no trabalho",
    "Primeiro eu preciso ver se consigo essas férias.",
    ["férias", "preciso ver no trabalho", "rh", "folga", "meu chefe", "escala"],
    "A data não trava a decisão. Reservo com flexibilidade e ajusto quando o RH confirmar.", "baixa", "fechamento"),
  o("00000000-0000-4000-8000-000000000008", "autoridade", "Autoridade / Cônjuge",
    "Preciso falar com meu cônjuge antes",
    "Preciso conversar com meu marido primeiro, ele decide comigo.",
    ["meu marido", "minha esposa", "meu cônjuge", "minha mulher", "falar com ele", "falar com ela", "decidir junto", "ver com ele", "ver com ela"],
    "Bora fazer quinze minutos com vocês dois juntos. Você não precisa virar minha porta-voz.", "alta", "fechamento"),
  o("00000000-0000-4000-8000-000000000009", "autoridade", "Autoridade / Cônjuge",
    "Preciso alinhar com o grupo que vai junto",
    "Somos quatro casais, preciso ver com todo mundo antes.",
    ["somos vários", "casais", "todo mundo junto", "vamos em grupo", "ver com o grupo", "os amigos"],
    "Você articula, eu vendo. Entro numa call com todos e travo o bloco de quartos hoje.", "media", "fechamento"),
  o("00000000-0000-4000-8000-000000000010", "confianca", "Confiança / Risco",
    "Nunca ouvi falar da agência",
    "Desculpa, mas eu nunca ouvi falar de vocês.",
    ["nunca ouvi falar", "não conheço", "vocês são confiáveis", "quem são vocês", "é seguro", "é golpe"],
    "Te mando CNPJ, cadastro no Mtur, depoimentos em vídeo e o contrato antes de qualquer pagamento.", "alta", "abertura"),
  o("00000000-0000-4000-8000-000000000011", "confianca", "Confiança / Risco",
    "Medo de pagar antecipado e não receber",
    "Pagar tudo antes me deixa inseguro, e se der problema?",
    ["pagar antes", "antecipado", "golpe", "e se der problema", "inseguro", "garantia", "calote"],
    "Você acumula vouchers em seu nome a cada etapa. Não está comprando confiança, está acumulando documento.", "alta", "proposta"),
  o("00000000-0000-4000-8000-000000000012", "confianca", "Confiança / Risco",
    "E se eu precisar cancelar, perco tudo?",
    "E se acontecer alguma coisa e eu precisar cancelar? Perco o dinheiro?",
    ["cancelar", "desistir", "imprevisto", "perco tudo", "reembolso", "remarcar", "se eu não puder ir", "cancelamento"],
    "Mostro a regra de cancelamento de cada linha por escrito, e cotamos seguro para o resto.", "media", "proposta"),
  o("00000000-0000-4000-8000-000000000013", "concorrente", "Concorrência",
    "Estou cotando com outra agência",
    "Estou vendo com outra agência também, quero comparar.",
    ["outra agência", "estou cotando", "comparar proposta", "tenho outro orçamento", "concorrente"],
    "Compare sim. Me manda a outra proposta que eu monto o quadro lado a lado, escopo por escopo.", "alta", "proposta"),
  o("00000000-0000-4000-8000-000000000014", "concorrente", "Concorrência",
    "Tenho um conhecido que é agente de viagens",
    "Meu primo trabalha com viagem, acho que vou com ele.",
    ["meu primo", "conhecido que trabalha", "amigo agente", "já tenho alguém", "indicação de amigo"],
    "Ele já operou esse destino nesse padrão quantas vezes esse ano? Repertório decide aqui.", "media", "diagnostico"),
  o("00000000-0000-4000-8000-000000000015", "concorrente", "Concorrência",
    "Sempre viajo com a mesma agência",
    "Eu já tenho a agência que sempre uso, faz anos.",
    ["sempre uso", "minha agência", "já tenho agência", "fidelidade", "faz anos que viajo com"],
    "Não vim pedir troca, vim pedir comparação em uma viagem. O que você mudaria na última?", "media", "abertura"),
  o("00000000-0000-4000-8000-000000000016", "pagamento", "Forma de Pagamento",
    "Quer saber de parcelamento",
    "E dá para parcelar em quantas vezes?",
    ["parcelar", "parcela", "quantas vezes", "dividir", "no cartão", "boleto", "financiar"],
    "Dá pra montar do jeito que caiba no seu mês. Quanto você imaginava por parcela?", "media", "proposta"),
  o("00000000-0000-4000-8000-000000000017", "sinal_compra", "Sinal de compra",
    "Pergunta como fechar / garantir",
    "Como faço para fechar? Quero garantir essa data.",
    ["como faço para fechar", "como eu faço pra fechar", "quero fechar", "quero garantir", "vamos fechar", "me manda o contrato", "qual o próximo passo", "tem disponibilidade", "tem vaga"],
    "Fecha agora comigo. Só preciso de dois dados e garanto sua vaga.", "alta", "fechamento"),
];
